#!/bin/bash
# Startup script for EC2 deployment
# Automatically detects EC2 public IP and configures services

set -e

echo "🚀 Starting TaskMaster on EC2..."
echo ""

# Get EC2 public IP using AWS metadata service
# This endpoint is only available inside EC2 instances
EC2_PUBLIC_IP=$(curl -s http://curl checkip.amazonaws.com 2>/dev/null || echo "")

if [ -z "$EC2_PUBLIC_IP" ]; then
  echo "❌ Could not detect EC2 public IP."
  echo "   Are you running on an EC2 instance?"
  echo "   Fallback: Using localhost"
  EC2_PUBLIC_IP="localhost"
fi

echo "✅ Detected Public IP: $EC2_PUBLIC_IP"
echo ""

# Update .env file with current EC2 IP
cat > .env << ENVFILE
# Auto-generated by start-ec2.sh
NODE_ENV=production
MONGO_ROOT_USER=admin
MONGO_ROOT_PASSWORD=SuperSecurePassword123!
CORS_ORIGIN=http://${EC2_PUBLIC_IP}:3000
VITE_API_URL=http://${EC2_PUBLIC_IP}:5000
ENVFILE

echo "📝 Updated .env with EC2 public IP"
echo ""

# Stop existing containers
echo "🛑 Stopping existing containers..."
docker compose down
docker system prune -af
docker compose down -v
# Rebuild frontend with new API URL
echo "🔨 Rebuilding frontend with API URL: http://${EC2_PUBLIC_IP}:5000"
docker compose build frontend --no-cache

# Start all services
echo "🚀 Starting all services..."
docker compose up -d

# Wait for services to be healthy
echo ""
echo "⏳ Waiting for services to be healthy..."
sleep 10

# Check status
docker compose ps

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📊 Access your application:"
echo "   Frontend:  http://${EC2_PUBLIC_IP}:3000"
echo "   Backend:   http://${EC2_PUBLIC_IP}:5000/health"
echo ""
echo "🔍 Check logs: docker compose logs -f"
