#!/bin/bash
# ═══════════════════════════════════════════════════════
# TaskMaster EC2 Bootstrap Script
# Installs Docker, Docker Compose, clones repo, starts app
# ═══════════════════════════════════════════════════════

set -e

exec > >(tee /var/log/user-data.log)
exec 2>&1

echo "=========================================="
echo "TaskMaster EC2 Bootstrap Starting..."
echo "Time: $(date)"
echo "=========================================="

# Update system
echo "1. Updating system packages..."
apt-get update -y
apt-get upgrade -y

# Install Docker
echo "2. Installing Docker..."
apt-get install -y ca-certificates curl gnupg lsb-release

# Add Docker GPG key
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker Engine
apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Add user to docker group
usermod -aG docker ${docker_user}

# Start and enable Docker
systemctl start docker
systemctl enable docker

# Verify Docker installation
docker --version
docker compose version

# Install Git
echo "3. Installing Git..."
apt-get install -y git

# Clone repository
echo "4. Cloning TaskMaster repository..."
cd /home/${docker_user}
if [ -d "devops-portfolio-3tier-app" ]; then
  rm -rf devops-portfolio-3tier-app
fi

# Clone as ubuntu user
sudo -u ${docker_user} git clone ${github_repo} devops-portfolio-3tier-app
cd devops-portfolio-3tier-app

# Get EC2 public IP (with IMDSv2 support)
echo "5. Detecting EC2 Public IP..."
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" -s 2>/dev/null || echo "")

if [ -n "$TOKEN" ]; then
  # IMDSv2
  EC2_PUBLIC_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" \
    -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null)
else
  # IMDSv1 fallback
  EC2_PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null)
fi

if [ -z "$EC2_PUBLIC_IP" ]; then
  echo "❌ ERROR: Could not detect EC2 public IP"
  exit 1
fi

echo "✅ Detected Public IP: $EC2_PUBLIC_IP"

# Create .env file with EC2 public IP
echo "6. Configuring environment..."
cat > .env << ENVFILE
# Auto-generated by Terraform user_data
# Generated at: $(date)
NODE_ENV=production
MONGO_ROOT_USER=admin
MONGO_ROOT_PASSWORD=SuperSecurePassword123!
CORS_ORIGIN=http://$EC2_PUBLIC_IP:3000
VITE_API_URL=http://$EC2_PUBLIC_IP:5000
ENVFILE

chown ${docker_user}:${docker_user} .env

echo "📝 Environment configuration:"
cat .env

# ═══════════════════════════════════════════════════════
# CRITICAL FIX: Rebuild frontend with correct API URL
# ═══════════════════════════════════════════════════════

echo "7. Building frontend with EC2 public IP..."
echo "   This ensures VITE_API_URL is correctly set"

# Pull latest images (for backend/db)
sudo -u ${docker_user} docker compose pull mongodb backend || true

# Build frontend with --no-cache to ensure fresh build
echo "   Building frontend container (this may take 2-3 minutes)..."
sudo -u ${docker_user} docker compose build frontend --no-cache

# Verify .env is correct before starting
echo "8. Verifying configuration..."
if grep -q "VITE_API_URL=http://$EC2_PUBLIC_IP:5000" .env; then
  echo "✅ VITE_API_URL correctly set to EC2 public IP"
else
  echo "❌ WARNING: VITE_API_URL not set correctly"
fi

# Start application
echo "9. Starting TaskMaster application..."
sudo -u ${docker_user} docker compose up -d

# Wait for containers to be healthy
echo "10. Waiting for containers to start..."
sleep 15

# Show status
echo "11. Container status:"
docker compose ps

# Show logs for debugging
echo "12. Recent frontend logs:"
docker compose logs frontend --tail 20

echo "13. Recent backend logs:"
docker compose logs backend --tail 20

# Test connectivity
echo "14. Testing services..."
if curl -sf http://localhost:5000/health > /dev/null 2>&1; then
  echo "✅ Backend is responding"
else
  echo "⚠️  Backend not responding yet (might still be starting)"
fi

if curl -sf http://localhost:3000 > /dev/null 2>&1; then
  echo "✅ Frontend is responding"
else
  echo "⚠️  Frontend not responding yet (might still be starting)"
fi

# Create a status file
cat > /home/${docker_user}/deployment-status.txt << STATUS
========================================
TaskMaster Deployment Status
========================================
Deployment Time: $(date)
EC2 Public IP: $EC2_PUBLIC_IP

URLs:
  Frontend: http://$EC2_PUBLIC_IP:3000
  Backend:  http://$EC2_PUBLIC_IP:5000/health

Environment:
$(cat .env)

Container Status:
$(docker compose ps)

========================================
STATUS

chown ${docker_user}:${docker_user} /home/${docker_user}/deployment-status.txt

echo ""
echo "=========================================="
echo "✅ Bootstrap Complete!"
echo "=========================================="
echo "Frontend: http://$EC2_PUBLIC_IP:3000"
echo "Backend:  http://$EC2_PUBLIC_IP:5000"
echo ""
echo "📋 Deployment details saved to:"
echo "   /home/ubuntu/deployment-status.txt"
echo ""
echo "🔍 Check logs with:"
echo "   docker compose logs -f"
echo "=========================================="
