#!/bin/bash
# ═══════════════════════════════════════════════════════
# TaskMaster EC2 Bootstrap Script
# Installs Docker, Docker Compose, clones repo, starts app
# ═══════════════════════════════════════════════════════

set -e


exec > >(tee /var/log/user-data.log)
exec 2>&1

echo "=========================================="
echo "TaskMaster EC2 Bootstrap Starting..."
echo "Time: $(date)"
echo "=========================================="


# Update system
echo "1. Updating system packages..."
apt-get update -y
apt-get upgrade -y

# Install Docker
echo "2. Installing Docker..."
apt-get install -y ca-certificates curl gnupg lsb-release


# Add Docker GPG key
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Add Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker Engine
apt-get update -y
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Add user to docker group
usermod -aG docker ${docker_user}

# Start and enable Docker
systemctl start docker
systemctl enable docker

# Verify Docker installation
docker --version
docker compose version

# Install Git
echo "3. Installing Git..."
apt-get install -y git

# Clone repository
echo "4. Cloning TaskMaster repository..."
cd /home/${docker_user}
if [ -d "devops-portfolio-3tier-app" ]; then
  rm -rf devops-portfolio-3tier-app
fi

# Clone as ubuntu user
sudo -u ${docker_user} git clone ${github_repo} devops-portfolio-3tier-app
cd devops-portfolio-3tier-app

# Get EC2 public IP
echo "5. Configuring environment..."
EC2_PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

# Create .env file
cat > .env << ENVFILE
# Auto-generated by Terraform user_data
NODE_ENV=production
MONGO_ROOT_USER=admin
MONGO_ROOT_PASSWORD=SuperSecurePassword123!
CORS_ORIGIN=http://$${EC2_PUBLIC_IP}:3000
VITE_API_URL=http://$${EC2_PUBLIC_IP}:5000
ENVFILE

chown ${docker_user}:${docker_user} .env

# Start application
echo "6. Starting TaskMaster application..."
sudo -u ${docker_user} docker compose up -d

# Wait for containers
sleep 10

# Show status
echo "7. Container status:"
docker compose ps

echo "=========================================="
echo "Bootstrap Complete!"
echo "Frontend: http://$${EC2_PUBLIC_IP}:3000"
echo "Backend:  http://$${EC2_PUBLIC_IP}:5000"
echo "=========================================="
